// Generated by firmware/generator/temperaments.py. Edit that file, not this one.
//
// Cents from equal temperament for pitch classes C, C#, D ... B, one row per
// temperament, in the order stored in presets (the temperament parameter).
// Every row has A at 0, so A sounds at the master tuning pitch in all of them.
#pragma once
#include <stdint.h>

const int8_t temperament_cents[][12] = {
  {  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0},   // 0 equal
  { 10, -14,   3,  21,  -3,  14, -10,   7, -17,   0,  17,  -7},   // 1 quarter-comma meantone
  { 16,  27,  20,  31,   2,  14,   6,  18,  29,   0,  12,   4},   // 2 five-limit just (C major)
  { -6,   8,  -2, -12,   2,  -8,   6,  -4,  10,   0, -10,   4},   // 3 pythagorean
  { 12,   2,   4,   6,   2,  10,   0,   8,   4,   0,   8,   4},   // 4 werckmeister III
  { 10,   0,   3,   4,  -3,   8,   0,   7,   2,   0,   6,  -1},   // 5 kirnberger III
  {  6,   0,   2,   4,  -2,   8,  -2,   4,   2,   0,   6,  -4},   // 6 vallotti
  {  6,  -4,   2,   0,  -2,   4,  -6,   4,  -2,   0,   2,  -4},   // 7 young no. 2
  {  8,  -2,   3,   2,  -3,   6,  -4,   5,   0,   0,   4,  -1},   // 8 kellner
  {  5,  -7,   2,  10,  -2,   7,  -5,   3,  -8,   0,   8,  -3},   // 9 sixth-comma meantone
};
const uint8_t temperament_count = sizeof(temperament_cents) / sizeof(temperament_cents[0]);
