name: Firmware Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'firmware/**'
      - '.github/workflows/firmware-tests.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'firmware/**'
      - '.github/workflows/firmware-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Cache PlatformIO
      uses: actions/cache@v4
      with:
        path: |
          ~/.platformio
          ~/.cache/pip
        key: ${{ runner.os }}-pio-${{ hashFiles('**/platformio.ini') }}
        restore-keys: |
          ${{ runner.os }}-pio-
          
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        
    - name: Run tests
      run: |
        cd firmware
        pio test -e native --verbose
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: firmware/.pio/test/

